server:
  port: 9003  # Port for the API gateway

spring:
  application:
    name: API-GATEWAY  # Name of the gateway application

  cloud:
    consul:
      host: localhost  # Consul host, usually localhost if running locally
      port: 8500  # Consul port (default is 8500)
      discovery:
        enabled: true  # Enable service discovery with Consul
        service-name: API-GATEWAY  # Service name registered with Consul
        health-check-path: /actuator/health  # Health check endpoint
        health-check-interval: 10s  # Interval for health checks
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}  # Unique instance ID

    gateway:
      discovery:
        locator:
          enabled: true  # Enable dynamic routing based on Consul services
          lower-case-service-id: true  # Convert service IDs to lower case
      routes:
        - id: USER-SERVICE  # Unique ID for user service route
          uri: http://localhost:9002 # Load balanced URI for user service
          predicates:
            - Path=/users/**  # Route path for user service

        - id: DEPARTMENT-SERVICE  # Unique ID for department service route
          uri: http://localhost:9001  # Load balanced URI for department service
          predicates:
            - Path=/departments/**  # Route path for department service


